---
- name: restart yum-cron
  service: name=yum-cron state=restarted

- name: restart server
  command: shutdown -r now "Reboot triggered by Ansible"
  async: 0
  poll: 0
  ignore_errors: true

- name: wait for server to restart
  local_action:
    module: wait_for host={{ inventory_hostname }} port=22 delay=1 timeout=300
    sudo: false
