---
- name: Add MariaDB repo
  yum_repository:
    name: mariadb
    description: MariaDB
    baseurl: http://yum.mariadb.org/10.1/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes

- name: Install MariaDB packages from MariaDB repo
  yum: name={{ item }} enablerepo=mariadb state=present
  with_items:
   - MariaDB-server
   - MariaDB-client
   - MySQL-python

# Stock MariaDB configuration is now pretty good.
# Nothing important to configure before we turn it on.
# We can tune it later using something like:
#   https://github.com/mattiabasone/tuning-primer

# But we do need to secure it.

- name: Update MariaDB root password for all root accounts
  mysql_user: name=root host_all=yes password={{ mariadb_root_passwd }}

- name: Create .my.cnf file with root password credentials
  template: src=client.cnf.j2 dest=/root/.my.cnf owner=root mode=0600 backup=yes

- name: Remove all anonymous user accounts from MariaDB
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: Remove the MariaDB test database
  mysql_db: db=test state=absent

- name: Enable mariadb now and in the future
  service: name=mariadb state=started enabled=yes
